[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".config/k9s/skins/rose-pine-dawn.yaml"]
    type = "file"
    url = "https://raw.githubusercontent.com/sasoria/k9s-theme/refs/heads/main/rose-pine-dawn.yaml"
    refreshPeriod = "168h"


