[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".zshrc"]
    type = "file"
    url = "https://raw.githubusercontent.com/grml/grml-etc-core/master/etc/zsh/zshrc"
    refreshPeriod = "168h"
[".config/fish/themes/Catppuccin Mocha.theme"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/fish/main/themes/Catppuccin%20Mocha.theme"
    refreshPeriod = "168h"
[".config/fish/themes/Catppuccin Latte.theme"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/fish/main/themes/Catppuccin%20Latte.theme"
    refreshPeriod = "168h"


