"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """\
    $time\
    $all\
    $line_break\
    $jobs\
    $character\
    """

[character]
format="$symbol "
success_symbol="[»](bold green)"
error_symbol="[»](bold red)"

[java]
disabled = true


[time]
disabled = false
time_format = "%T"
style = "bold blue"
format="[$time]($style) "

[aws]
style = "bold #E06C75"

[cmd_duration]
style = "bold #E5C07B"
min_time=6_000

[directory]
style = "bold #98C379"

[git_branch]
style = "bold #C678DD"

[git_status]
style = "bold #E06C75"

[hostname]
style = "bold #C678DD"

[username]
format = "[$user]($style) on "
style_user = "bold #61AFEF"

[kubernetes]
disabled = false

[docker_context]
disabled = true
[kotlin]
disabled = true
[gradle]
disabled = true

[battery]
disabled = true
