add_newline = false

format = """\
    $time\
    $username\
    $hostname\
    $kubernetes\
    $directory\
    $hg_branch\
    $package\
    $golang\
    $java\
    $python\
    $rust\
    $terraform\
    $zig\
    $nix_shell\
    $memory_usage\
    $aws\
    $env_var\
    $crystal\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $character\
    """

[character]
format="$symbol "
success_symbol="[»](bold  #50fa7b)"
error_symbol="[»](bold #ff5555)"

[java]
disabled = true


[time]
disabled = false
time_format = "%T"
style = "bold blue"
format="[$time]($style) "

[aws]
style = "bold #ffb86c"

[cmd_duration]
style = "bold #f1fa8c"
min_time=6_000

[directory]
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"
