"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """\
    $time\
    $all\
    $line_break\
    $jobs\
    $character\
    """

[character]
format="$symbol "
success_symbol="[»](bold green)"
error_symbol="[»](bold red)"

[java]
disabled = true


[time]
disabled = false
time_format = "%T"
style = "bold blue"
format="[$time]($style) "

[aws]
style = "bold #f38ba8"

[cmd_duration]
style = "bold #f9e2af"
min_time=6_000

[directory]
style = "bold #a6e3a1"

[git_branch]
style = "bold #cba6f7"

[git_status]
style = "bold #f38ba8"

[hostname]
style = "bold #cba6f7"

[username]
format = "[$user]($style) on "
style_user = "bold #74c7ec"

[kubernetes]
disabled = true

[docker_context]
disabled = true

[battery]
disabled = true
