add_newline = false

format = """\
    $time\
    $username\
    $hostname\
    $kubernetes\
    $directory\
    $hg_branch\
    $python\
    $nix_shell\
    $memory_usage\
    $aws\
    $env_var\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $character\
    """

[character]
format="$symbol "
success_symbol="[»](bold  #98C379)"
error_symbol="[»](bold #E06C75)"

[java]
disabled = true


[time]
disabled = false
time_format = "%T"
style = "bold blue"
format="[$time]($style) "

[aws]
style = "bold #E06C75"

[cmd_duration]
style = "bold #E5C07B"
min_time=6_000

[directory]
style = "bold #98C379"

[git_branch]
style = "bold #C678DD"

[git_status]
style = "bold #E06C75"

[hostname]
style = "bold #C678DD"

[username]
format = "[$user]($style) on "
style_user = "bold #61AFEF"
